### ISSUE TITLE
mem_rdata_latched_noshuffle could be X value

### ISSUE THREAD

**Issue by jillleon007** [cliffordwolf/picorv32#107]
In the README.md,line390-399,about "read transfer"

It is said like this:
"There is no need for an external wait cycle. The memory read can be implemented
asynchronously with `mem_ready` going high in the same cycle as `mem_valid`, or
`mem_ready` being tied to constant 1."

In the source code I find this:

> 	**assign mem_xfer = (mem_valid && mem_ready) || (mem_la_use_prefetched_high_word && mem_do_rinst);
> 	...
> 	...
> 	assign mem_rdata_latched_noshuffle = (mem_xfer || LATCHED_MEM_RDATA) ? mem_rdata : mem_rdata_q**;

it seems that when mem_valid&mem_ready are high, the mem_radata_latched_noshuffle will be assigned mem_rdata' value

In pico's design. if mem_rdata is avaliable, mem_ready must be high.
But in my simulation tools, I found when mem_valid&mem_ready are high, the mem_rdata could be X value! And because the mem_xfer is high, the X value will be transfer to mem_rdata_latched_noshuffle. In next clock,the X value will be assigned to instr_jalr. The core will read a unknown instruction,and it will be into a trap.

The code shown below

> 	**
> assign mem_rdata_latched = COMPRESSED_ISA && mem_la_use_prefetched_high_word ? {16'bx, mem_16bit_buffer} :
> 			COMPRESSED_ISA && mem_la_secondword ? {mem_rdata_latched_noshuffle[15:0], mem_16bit_buffer} :
> 			COMPRESSED_ISA && mem_la_firstword ? {16'bx, mem_rdata_latched_noshuffle[31:16]} : mem_rdata_latched_noshuffle;
>         instr_jalr    <= mem_rdata_latched[6:0] == 7'b1100111 && mem_rdata_latched[14:12] == 3'b000;
> **

![Uploading 1.png…]()

**Comment by cliffordwolf** [comment]
Unfortunately you do not include a simulation test bench that would demonstrate the issue. So I can't reproduce what you are seeing therefore there is really nothing I could do.
