### ISSUE TITLE
Question about default 'starting' location for instruction memory requests after reset

### ISSUE THREAD

**Issue by zwabbit** [cliffordwolf/picorv32#11]
The privileged spec states that the reset vector is address 0x200, and when doing a bare-metal compile that's also where the first instruction is located. Currently after your processor goes out of reset it starts querying for instructions at address 0. Is this intentional?

**Comment by cliffordwolf** [comment]
The start address is configured using the PROGADDR_RESET parameter:

https://github.com/cliffordwolf/picorv32#progaddr_reset-default--32h-0000_0000
