### ISSUE TITLE
picorv32 memory mapping

### ISSUE THREAD

**Issue by drtrigon** [cliffordwolf/picorv32#116]
As mentioned in #95 we are setting up fpgarduino to work with this picorv32. For that we currently need some insight how the memory is mapped and whether it is possible to put code into RAM and execute from there?

**Comment by cliffordwolf** [comment]
You can put code in RAM, In fact, PiucoRV32 doesn't know which memory regions are RAM and which are something else. There is no universal memory map for PicoRV32. As far as the processor is concerned it's just a flat 32 bit address space. You decide the memory map in the SoC that you built.
