### ISSUE TITLE
RISC-V tests

### ISSUE THREAD

**Issue by aignacio** [cliffordwolf/picorv32#118]
Hi @Cliffordwolf,
Thanks for the excellent job with this core, so I'm trying to generate a .hex file (to use as input in vvp simulation) of the assembly programs inside the /tests folder, but I'm facing some issues with undefined reference for the global symbols of TEST_...RET of the test cases in the programs (ori_ret, addi_ret...) Would you have some tips to compile these programs and link all into a single elf?

**Comment by cliffordwolf** [comment]
The tests folder doesn't contain complete programs. Instead, those are functions used in the demo firmware. Simply running `make` will build the demo firmware and run it in a simulation.

The `make` output lines `lui..OK`, `auipc..OK`, `j..OK`, and so forth are the output for those tests.
