### ISSUE TITLE
Can you upload the max frequency that picorv32 could run on Xilinx Atrix-7?

### ISSUE THREAD

**Issue by hyf6661669** [cliffordwolf/picorv32#120]
At present, only results of K7, V7, KU, VU, KU+, VU+ is displayed in README.MD. Sorry but I don't have a Vivado license. So it is very helpful if you can upload the result of A7.

Thanks.

**Comment by shufps** [comment]
Vivado license is free for Artix S7 - afaik. Is it not?

**Comment by cliffordwolf** [comment]
What @shufps said.
