### ISSUE TITLE
What MMU would you recommend with this?

### ISSUE THREAD

**Issue by WarlockD** [cliffordwolf/picorv32#125]
I have been playing around with this on my ICE40 using this chinese 8M Quad-SPI PSRAM and it works great.

I was thinking of building some kind of kernel that utilizes real processes and was wondering what kind of small/simple MMU would you recommend.  I still have 30% of the chip available but wanted to be stingy.  I was thinking of a simple 74LS612 type MMU controller with masks for KERNEL/USER space.  The idea of putting in a full TLB with caching seems a bit much for trying to keep it simple.

I was wondering on your thoughts on this.  Is it practical to make a simple MMU just for size, or is it better to just cut in the normal one from the RISCV isa?

**Comment by cliffordwolf** [comment]
I wouldn't recommend any MMU for PicoRV32. It's a tiny embedded core aimed at applications that traditionally have no need for MMUs.
