### ISSUE TITLE
README typo(s).

### ISSUE THREAD

**Issue by kuzminrobin** [cliffordwolf/picorv32#129]
At https://github.com/cliffordwolf/picorv32 (in `README.md`) I see:
> A PCPI core that implements the \`MUL[H[SU

I expected:
> A PCPI core that implements the \`MUL[H[SU **|U]]** \`

(the fragment **|U]]** is missing).

**Comment by cliffordwolf** [comment]
Oh, it was there. The github markdown implementation just thought the `|` terminated the table cell. :) Fixed in d124abbacd655e449becb9a05cb70ff45c50fa9b.
