### ISSUE TITLE
undefined reference to `memcpy'

### ISSUE THREAD

**Issue by JunnanLi** [cliffordwolf/picorv32#149]
Hi,
When I compile my C program, it occurs the following problem: "undefined reference to `memcpy'". The C programm is:

int array[10] = {0,1,2,3,4,5,6,7,8,9};
for (int i = 0; i < 10; ++i){
	print_dec(array[i]);
}

**Comment by luismarques** [comment]
You need to link with the C standard library. If that advice doesn't help, you'll probably need to provide more details about what commands you are running and so on. But this issue seems out of scope of the picorv32 project.

**Comment by JunnanLi** [comment]
Thanks
