### ISSUE TITLE
simulation error

### ISSUE THREAD

**Issue by bilkarpooja** [cliffordwolf/picorv32#160]
hello this is pooja since from a couple of weeks i m working on picorv32 code bt i m facing one error after simulating the picosoc folder of the picorv32 ,plz  help me to debud this error. the error snap is below
![image](https://user-images.githubusercontent.com/53936697/80277511-0798cb00-870d-11ea-9c0a-d3f2c568378c.png)

**Comment by cliffordwolf** [comment]
See my reply to #159.
