### ISSUE TITLE
Help me to locate 1Read 1Write picorv_register module

### ISSUE THREAD

**Issue by zeeshanrafique23** [cliffordwolf/picorv32#178]
I hear 20th-oct talk of Open-RAM, they said that picorv32 is using a register file that has a 1R and 1W port. I searched in the picosoc.v and in the whole repo but found nothing like that anyone who can search it and send the link in a comment.

**Comment by mguthaus** [comment]
https://github.com/cliffordwolf/picorv32/blob/master/picosoc/picosoc.v

Lines 222-257.

**Comment by mguthaus** [comment]
Also, this option:
https://github.com/cliffordwolf/picorv32#enable_regs_dualport-default--1

**Comment by zeeshanrafique23** [comment]
Hey thanks, Matthew I am just listening to you...

**Comment by zeeshanrafique23** [comment]
If we have one read port should they stall for another register read operation or they are using any other technique?

**Comment by mguthaus** [comment]
I would assume so. The code is all there so you can check.

**Comment by zeeshanrafique23** [comment]
Thanks Prof.  Matt
