### ISSUE TITLE
Tagged release of picorv32

### ISSUE THREAD

**Issue by olofk** [cliffordwolf/picorv32#23]
I'm considering updating the picorv32 core for the FuseSoC standard library, but it would be great to have a tagged release that I can use

**Comment by cliffordwolf** [comment]
There are a couple of open todo items that I'd like to address first. As soon as this is done I'll tag a release.

**Comment by olofk** [comment]
Cool. I'll prepare the stuff on the FuseSoC side in the meantime

**Comment by impedimentToProgress** [comment]
I second this.  Hopefully FuseSoC has a AXI4-Wishbone bridge.  It would be nice to have a RISC-V SoC with DDR and Ethernet support.

**Comment by cliffordwolf** [comment]
Just tagged v1.0.
