### ISSUE TITLE
custom0 opcode not defined in riscv-gnu-toolchain

### ISSUE THREAD

**Issue by bcdonovan** [cliffordwolf/picorv32#26]
How is the `custom0` opcode defined for RV32 toolchain? 

I am trying to work with your IRQ examples in the firmware directory. 

When I compile with the riscv32im toolchain I am getting `unrecognized opcode custom0` errors:

```
start.S: Assembler messages:
start.S:22: Error: unrecognized opcode `custom0 2,x1,0,1'
start.S:23: Error: unrecognized opcode `custom0 3,x2,0,1'
start.S:28: Error: unrecognized opcode `custom0 x2,0,0,0'
start.S:31: Error: unrecognized opcode `custom0 x2,2,0,0'
start.S:34: Error: unrecognized opcode `custom0 x2,3,0,0'
start.S:77: Error: unrecognized opcode `custom0 a1,1,0,0'
start.S:88: Error: unrecognized opcode `custom0 0,x2,0,1'
start.S:91: Error: unrecognized opcode `custom0 1,x2,0,1'
start.S:94: Error: unrecognized opcode `custom0 2,x2,0,1'
start.S:126: Error: unrecognized opcode `custom0 x1,1,0,0'
start.S:127: Error: unrecognized opcode `custom0 x2,2,0,0'
start.S:129: Error: unrecognized opcode `custom0 0,0,0,2'
```

Does the `custom0` opcode need to be patched into the [binutils riscv-opc.c](https://github.com/riscv/riscv-binutils-gdb/blob/riscv-next/opcodes/riscv-opc.c) file?

**Comment by cliffordwolf** [comment]
Support for `customN` has been removed in riscv-gnu-toolchain. See https://github.com/riscv/riscv-gnu-toolchain/issues/190 for details.

The [PicoRV32 riscv-gnu-toolchain-update branch](https://github.com/cliffordwolf/picorv32/tree/riscv-gnu-toolchain-update) contains some preliminary work to work around the changes in recent versions in riscv-gnu-toolchain. Until this work is finished, use version 7e48594 of riscv-gnu-toolchain, as described in the [PicoRV32 README file](https://github.com/cliffordwolf/picorv32#building-a-pure-rv32i-toolchain).
