### ISSUE TITLE
Reset coding style

### ISSUE THREAD

**Issue by e19293001** [cliffordwolf/picorv32#27]
I just got started in building my own test bench for the
picorv32.v and noticed that there are 'bx values on the output
ports of picorv32 after the reset. Would it be a good coding
style in adding initial values for the FF output ports?

**Comment by cliffordwolf** [comment]
There are `'bx` values for (some of the) the outputs that have undef values at that cycle. It is good and important to have those `'bx` values as they allow you to see if your environment is using those values in cycles where it shouldn't.
