### ISSUE TITLE
Interpreting mem_wstrb

### ISSUE THREAD

**Issue by neuschaefer** [cliffordwolf/picorv32#4]
Hi,

I'm trying to understand the PicoRV32 native memory interface. How should `mem_wstrb` be interpreted in the `!= 0` case?

**Comment by cliffordwolf** [comment]
The 4 bits of `mem_wstrb` are write enables for the four bytes in the addressed word. Only the 8 values `0000`, `1111`, `1100`, `0011`, `1000`, `0100`, `0010`, and `0001` are possible, i.e. no write, write 32 bits, write upper 16 bits, write lower 16, or write a single byte respectively.

I've now also added this paragraph to REAMDE.md in commit 3ccbf6877e124989d415be9a3c8eaa38b02bdb7c.

**Comment by neuschaefer** [comment]
Thanks!
