### ISSUE TITLE
torture fails

### ISSUE THREAD

**Issue by riscveval** [cliffordwolf/picorv32#44]
Hi when i am trying to run torture it shows following error
bash test.sh
+ test -f config.vh
+ test -f test.S
++ sed '/march=/ ! d; s,^// ,-,;' config.vh
+ riscv32-unknown-elf-gcc -m32 -march=RV32IMC -ffreestanding -nostdlib -Wl,-Bstatic,-T,sections.lds -o test.elf test.S
riscv32-unknown-elf-gcc: error: unrecognized command line option '-m32'
make: *** [test] Error 1

Note : Give your suggestion to resolve this issue.

**Comment by cliffordwolf** [comment]
Fixed in 2bc93eb.
