### ISSUE TITLE
PicoRV32 Documents

### ISSUE THREAD

**Issue by riscveval** [cliffordwolf/picorv32#47]
HI, I am interested to learn PicoRV32, So Can you update Architecture & Pipeline, Datasheet for PicoRV32?

**Comment by cliffordwolf** [comment]
I think the README is pretty clear that PicoRV32 is not pipelined (there is a whole chapter on CPI performance). Regarding "Architecture": I don't know what you want to know. If you have specific questions that are not answered by the documentation yet: Please just bring them up here and I'll add to the documentation, but you have to ask specific questions!

**Comment by rebek-007** [comment]
Is there a reason you have not pipelined PicoRV32 ? I want to take this oppurtunity to create a pipelined version.
