### ISSUE TITLE
asm call needs volatile

### ISSUE THREAD

**Issue by wallclimber21** [cliffordwolf/picorv32#49]
https://github.com/cliffordwolf/picorv32/blob/31588b871e0258f28a6daa5a34a6ad53ab11f267/dhrystone/stdlib.c#L29

Probably not an issue in your use case, but I had this piece of code compiled way because of the missing volatile:

```
unsigned int start_time = time();
unsigned int elapsed_time = start_time;
while (elapsed_time < MS_TO_CYCLES(100)){
    elapsed_time = time() - start_time;
}
```

volatile is also missing here:
https://github.com/cliffordwolf/picorv32/blob/31588b871e0258f28a6daa5a34a6ad53ab11f267/firmware/stats.c#L31

**Comment by cliffordwolf** [comment]
Fixed in dda7db2.
