### ISSUE TITLE
Is there a way to simulate the CPU + DRAM memory latencies with this repository?

### ISSUE THREAD

**Issue by robsmi1974nyc** [cliffordwolf/picorv32#55]
It would be interesting to do that to get more realistic performance metrics, even if a simplistic 100 cycle delay to get to main memory.

**Comment by frantony** [comment]
Please see https://github.com/open-design/riscv-soc-cores/blob/master/cores/picorv32-wb-soc/bench/picorv32_wb_soc_tb.v.

picorv32_wb_soc uses picorv32 with Wishbone connector and wb_sdram_ctrl.

**Comment by cliffordwolf** [comment]
PicoRV32 has no caches. If you have a 100 cycles memory latency then it will take 100 cycles for a single instruction (200 cycles for memory load, memory store, and branches taken).

If you want reasonable performance with DRAM then you will need to write your own cache IP and a testbench for that which you can use to simulate performance and check that it is working correctly.
