### ISSUE TITLE
Cannot find module SB_IO

### ISSUE THREAD

**Issue by Sebas95** [cliffordwolf/picorv32#58]
I was trying to adapt the hx8kdemo for Zedboard, but when I try to construct the project in Vivado the module flash_io_buf doesn´t appears.

**Comment by cliffordwolf** [comment]
As the file name suggest and the picosoc readme states explicitly, this file is targeting the iCE40 architecture. Obviously you have to have to replace the iCE40 technology primitives with the appropriate primitives of your target architecture if you want to port it to a different type of FPGA.
