### ISSUE TITLE
Incorrect handling of SBREAK/ILLNSN with PCPI

### ISSUE THREAD

**Issue by stevekerrison** [cliffordwolf/picorv32#8]
I'm trying to put a minimal example of this together (or a patch if I get there quicker), but won't get a chance until tomorrow. I leave this here for now as a test of my own sanity.

If PCPI is enabled and an illegal instruction or `sbreak` occur, upon `retirq`, the signal `pcpi_valid` remains asserted. The eventual effect of this is that when the next valid PCPI instruction comes along, it causes another `SBREAK` IRQ to occur, presumably because the PCPI timeout never got reset.

I actually want to handle `ecall`, and I guess I could do it with another PCPI extension, but that seems like a less graceful solution.

**Comment by stevekerrison** [comment]
I have now tested this as a limited example in simulation, and in my normal use case on FPGA, and the behaviour is now as expected.

**Comment by cliffordwolf** [comment]
In current git head ecall and ebreak now do not wait for the PCPI timeout. Also: q0 in IRQ handler (IRQ return address) now encodes if the interrupted instruction is a 16 or 32 bit opcode, simplifying decoding of the instruction that caused the IRQ. See firmware/irq.c handling of IRQ 2 (the block at "`if ((irqs & 6) != 0)`") for example code.

**Comment by stevekerrison** [comment]
That's great, thanks very much for the additional patch.
