### ISSUE TITLE
dhrystone wrong

### ISSUE THREAD

**Issue by chlizheng** [cliffordwolf/picorv32#80]
Hi,
  I have used the given dhrystone.Because I have no iverilog, I change it to vcs tool.But aftr nrue it,when I check the result wave,it just stop to read data at 18382 cycles, compute by 100*10^6/(1757*18382) is too large.Do you know how to get the right dhrystone.

**Comment by cliffordwolf** [comment]
You probably have an old buggy version of VCS (see #53). I can't help you beyond that because I don't have VCS. iverilog is free and open source, so there should be no problem for you to install it.
