### ISSUE TITLE
Example cxxdemo needs regs 16-31

### ISSUE THREAD

**Issue by hutch31** [cliffordwolf/picorv32#83]
The example code for cxxdemo is compiled using the rv32ic compiler, which I believe uses the full 32 registers of the instruction set.  I had to enable the high regs in the testbench, otherwise it simply gave a TRAP exit.

With attached patch below test case passes.
[testbench.v.patch.txt](https://github.com/cliffordwolf/picorv32/files/2341516/testbench.v.patch.txt)

**Comment by cliffordwolf** [comment]
`ENABLE_REGS_16_31 = 1` is already the default value for `ENABLE_REGS_16_31`.

![image](https://user-images.githubusercontent.com/619764/44945353-db1d9600-ade7-11e8-9dd9-10171b9180c9.png)

No need to set it explicitly.

**Comment by cliffordwolf** [comment]
> and didn't realize I hadn't set it back to defaults

No worries. I had assumed it was something like that.
